# Generated by Django 5.1.4 on 2024-12-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="national_id",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="profile_pics/"
            ),
        ),
        migrations.AddField(
            model_name="taxi",
            name="plate_number",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="taxi",
            name="vehicle_description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="taxi",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taxi",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
