# Generated by Django 5.1.4 on 2025-01-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxis", "0004_ride"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="origin_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="origin_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
