# Generated by Django 5.1.4 on 2025-01-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxis", "0005_ride_origin_latitude_ride_origin_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="destination_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="destination_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
