# Generated by Django 5.1.4 on 2025-01-15 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxis", "0006_ride_destination_latitude_ride_destination_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="ride",
            name="destination_latitude",
        ),
        migrations.RemoveField(
            model_name="ride",
            name="destination_longitude",
        ),
        migrations.CreateModel(
            name="RideDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=255)),
                ("destination_latitude", models.FloatField(blank=True, null=True)),
                ("destination_longitude", models.FloatField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="taxis.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
