# Generated by Django 5.1.4 on 2025-02-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxis", "0008_ride_notified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Cliente"),
                    ("driver", "Taxista"),
                    ("admin", "Administrador"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
