# Generated by Django 5.1.4 on 2025-02-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxis", "0009_alter_appuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxi",
            name="direccion_origen",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
