# Generated by Django 5.2 on 2025-06-14 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0010_taxi_direccion_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexionWebSocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('driver', 'Conductor'), ('customer', 'Cliente'), ('central', 'Central')], max_length=20)),
                ('channel_name', models.CharField(help_text='Identificador interno del canal WebSocket', max_length=255, unique=True)),
                ('room_name', models.CharField(blank=True, help_text='Nombre del grupo WebSocket (ej. carrera_23)', max_length=100, null=True)),
                ('conectado', models.BooleanField(default=True, help_text='Si la conexión está activa o no')),
                ('ultima_conexion', models.DateTimeField(auto_now=True, help_text='Última vez que se conectó')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_conexiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexión WebSocket',
                'verbose_name_plural': 'Conexiones WebSocket',
                'ordering': ['-ultima_conexion'],
            },
        ),
    ]
