# Generated by Django 5.2 on 2025-06-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0011_conexionwebsocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
