# Generated by Django 5.2 on 2025-06-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0012_appuser_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
