# Generated by Django 5.2 on 2025-06-21 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0013_appuser_last_latitude_appuser_last_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True)),
                ('paso_actual', models.CharField(default='inicio', max_length=50)),
                ('datos', models.JSONField(default=dict)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
