# Generated by Django 5.2 on 2025-10-28 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0015_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('incoming_messages', models.IntegerField(default=0)),
                ('outgoing_messages', models.IntegerField(default=0)),
                ('new_conversations', models.IntegerField(default=0)),
                ('active_conversations', models.IntegerField(default=0)),
                ('completed_conversations', models.IntegerField(default=0)),
                ('rides_requested', models.IntegerField(default=0)),
                ('rides_completed', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estadística de WhatsApp',
                'verbose_name_plural': 'Estadísticas de WhatsApp',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_info', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpush_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Número de teléfono con código de país (+593...)', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Nombre del contacto', max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('waiting', 'Esperando respuesta'), ('completed', 'Completada'), ('abandoned', 'Abandonada')], default='active', max_length=20)),
                ('state', models.CharField(choices=[('inicio', 'Inicio'), ('esperando_origen', 'Esperando origen'), ('esperando_destino', 'Esperando destino'), ('confirmando_carrera', 'Confirmando carrera'), ('carrera_activa', 'Carrera activa')], default='inicio', help_text='Estado actual de la conversación', max_length=30)),
                ('data', models.JSONField(default=dict, help_text='Datos temporales de la conversación (origen, destino, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('ride', models.ForeignKey(blank=True, help_text='Carrera asociada (si existe)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='taxis.ride')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario registrado (si existe)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación de WhatsApp',
                'verbose_name_plural': 'Conversaciones de WhatsApp',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Entrante'), ('outgoing', 'Saliente')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('location', 'Ubicación'), ('image', 'Imagen'), ('audio', 'Audio'), ('document', 'Documento')], default='text', max_length=20)),
                ('content', models.TextField(help_text='Contenido del mensaje')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadatos adicionales (coordenadas, URLs, etc.)')),
                ('message_id', models.CharField(blank=True, help_text='ID del mensaje de WASender', max_length=255, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='taxis.whatsappconversation')),
            ],
            options={
                'verbose_name': 'Mensaje de WhatsApp',
                'verbose_name_plural': 'Mensajes de WhatsApp',
                'ordering': ['created_at'],
            },
        ),
    ]
