# Generated by Django 5.0.14 on 2025-12-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0002_fcmtoken'),
        ('taxis', '0017_chatmessage'),
    ]

    operations = [
    ]
