# Generated by Django 5.0.14 on 2025-12-27 18:40

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0020_chatmessage_media_url_chatmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el conductor fue aprobado', null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Administrador que aprobó al conductor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appuser',
            name='driver_number',
            field=models.CharField(blank=True, help_text='Número de unidad del conductor (ej: 001, 002, 003)', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='driver_status',
            field=models.CharField(choices=[('pending', 'Pendiente de Aprobación'), ('approved', 'Aprobado'), ('suspended', 'Suspendido'), ('rejected', 'Rechazado')], default='pending', help_text='Estado de aprobación del conductor', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comisión cobrada por la plataforma (calculada automáticamente)', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la cooperativa', max_length=200)),
                ('slug', models.SlugField(help_text='URL única: deaquipalla.com/taxi-oro', unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción de la cooperativa', null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, help_text='Logo de la cooperativa', max_length=255, null=True, verbose_name='image')),
                ('primary_color', models.CharField(default='#FFD700', help_text='Color primario en formato hexadecimal (#FFD700)', max_length=7)),
                ('secondary_color', models.CharField(default='#000000', help_text='Color secundario en formato hexadecimal (#000000)', max_length=7)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Ecuador', max_length=100)),
                ('plan', models.CharField(choices=[('owner', 'Propietario'), ('basic', 'Básico'), ('standard', 'Estándar'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Prueba'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('canceled', 'Cancelado')], default='trial', max_length=20)),
                ('max_drivers', models.IntegerField(default=10, help_text='Número máximo de conductores permitidos')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=29.0, help_text='Tarifa mensual en USD', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión por carrera (0-100)', max_digits=5)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='Fecha de fin del período de prueba', null=True)),
                ('subscription_starts_at', models.DateTimeField(blank=True, help_text='Fecha de inicio de la suscripción', null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, help_text='Fecha de fin de la suscripción', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Cooperativa a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='taxis.organization'),
        ),
        migrations.AddField(
            model_name='ride',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Cooperativa que gestiona esta carrera', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='taxis.organization'),
        ),
    ]
