# Generated by Django 5.0.14 on 2025-12-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0021_appuser_approved_at_appuser_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='billing_address',
            field=models.TextField(blank=True, help_text='Dirección de facturación'),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='Email para facturación', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_phone_display',
            field=models.CharField(blank=True, help_text='Teléfono de contacto para mostrar', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de suspensión', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Razón de la suspensión'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(blank=True, help_text='RUC o identificación fiscal', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisiones totales cobradas', max_digits=12),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ingresos totales generados', max_digits=12),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_rides',
            field=models.IntegerField(default=0, help_text='Total de carreras completadas'),
        ),
        migrations.AddField(
            model_name='organization',
            name='welcome_message',
            field=models.TextField(blank=True, help_text='Mensaje de bienvenida personalizado'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Número de factura único (ej: INV-2025-001)', max_length=50, unique=True)),
                ('period_start', models.DateField(help_text='Inicio del período facturado')),
                ('period_end', models.DateField(help_text='Fin del período facturado')),
                ('subscription_fee', models.DecimalField(decimal_places=2, help_text='Tarifa de suscripción mensual', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, help_text='Comisiones cobradas en el período', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Monto total a pagar', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de emisión')),
                ('due_date', models.DateField(help_text='Fecha de vencimiento')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Fecha de pago', null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Archivo PDF de la factura', null=True, upload_to='invoices/')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales')),
                ('organization', models.ForeignKey(help_text='Cooperativa facturada', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='taxis.organization')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issued_at'],
            },
        ),
    ]
