# Generated by Django 5.0.14 on 2025-12-30 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0022_organization_billing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceNegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Dirección de origen', max_length=255)),
                ('origin_latitude', models.FloatField(blank=True, null=True)),
                ('origin_longitude', models.FloatField(blank=True, null=True)),
                ('destination', models.CharField(help_text='Dirección de destino', max_length=255)),
                ('destination_latitude', models.FloatField(blank=True, null=True)),
                ('destination_longitude', models.FloatField(blank=True, null=True)),
                ('suggested_price', models.DecimalField(decimal_places=2, help_text='Precio sugerido por el sistema', max_digits=10)),
                ('proposed_price', models.DecimalField(decimal_places=2, help_text='Precio propuesto por el cliente', max_digits=10)),
                ('counter_offer_price', models.DecimalField(blank=True, decimal_places=2, help_text='Contraoferta de la central', max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio final acordado', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('counter_offered', 'Contraoferta'), ('client_accepted', 'Cliente Aceptó'), ('client_rejected', 'Cliente Rechazó'), ('expired', 'Expirada'), ('ride_created', 'Carrera Creada')], default='pending', max_length=20)),
                ('response_message', models.TextField(blank=True, help_text='Mensaje de la central al cliente', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Fecha de expiración (15 minutos después de crear)')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='price_negotiations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Cooperativa que gestiona esta negociación', on_delete=django.db.models.deletion.CASCADE, related_name='price_negotiations', to='taxis.organization')),
                ('responded_by', models.ForeignKey(blank=True, help_text='Admin/Central que respondió', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_negotiations_responded', to=settings.AUTH_USER_MODEL)),
                ('ride', models.OneToOneField(blank=True, help_text='Carrera creada después de aceptar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiation', to='taxis.ride')),
            ],
            options={
                'verbose_name': 'Negociación de Precio',
                'verbose_name_plural': 'Negociaciones de Precio',
                'ordering': ['-created_at'],
            },
        ),
        # InvitationCode ya existe en la BD, se omite su creación
    ]
