# Generated by Django 5.0.14 on 2025-12-30 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0023_pricenegotiation_invitationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='car_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='car_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único de invitación (ej: TAXI-ABC123)', max_length=12, unique=True)),
                ('role', models.CharField(choices=[('customer', 'Cliente'), ('driver', 'Conductor')], help_text='Rol para el que es válido este código', max_length=10)),
                ('max_uses', models.IntegerField(default=0, help_text='Número máximo de usos (0 = ilimitado)')),
                ('current_uses', models.IntegerField(default=0, help_text='Número de veces que se ha usado')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración (null = sin expiración)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si el código está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre este código')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin que creó el código', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitation_codes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organización que genera el código', on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='taxis.organization')),
            ],
            options={
                'verbose_name': 'Código de Invitación',
                'verbose_name_plural': 'Códigos de Invitación',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='taxis_invit_code_fdaafc_idx'), models.Index(fields=['organization', 'role'], name='taxis_invit_organiz_66542e_idx')],
            },
        ),
    ]
