# Generated by Django 5.0.14 on 2026-01-07 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0024_taxi_car_color_taxi_car_model_taxi_car_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Versión del APK (ej: 1.0.0, 1.1.0)', max_length=20, unique=True)),
                ('apk_file', models.FileField(help_text='Archivo APK de la aplicación', upload_to='driver_apps/')),
                ('release_notes', models.TextField(blank=True, help_text='Notas de la versión (qué hay de nuevo)')),
                ('is_active', models.BooleanField(default=True, help_text='Si esta versión está activa para descarga')),
                ('is_latest', models.BooleanField(default=False, help_text='Si es la versión más reciente')),
                ('min_android_version', models.CharField(default='5.0', help_text='Versión mínima de Android requerida', max_length=10)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('downloads_count', models.IntegerField(default=0, help_text='Número de descargas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aplicación de Conductor',
                'verbose_name_plural': 'Aplicaciones de Conductor',
                'ordering': ['-created_at'],
            },
        ),
    ]
