# Generated by Django 5.0.14 on 2026-01-07 01:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0025_driverapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverapp',
            name='apk_file',
            field=models.FileField(help_text='Archivo APK de la aplicación', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\H P\\OneDrive\\Imágenes\\virtual\\proyecto_completo\\media'), upload_to='driver_apps/'),
        ),
    ]
