# Generated by Django 5.0.14 on 2026-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('taxis', '0025_appuser_vehicle_brand_appuser_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='driver_number',
            field=models.CharField(blank=True, help_text='Número de unidad del conductor (ej: 001, 002, 003)', max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.UniqueConstraint(condition=models.Q(('driver_number__isnull', False)), fields=('organization', 'driver_number'), name='unique_driver_number_per_organization'),
        ),
    ]
