# Generated by Django 5.0.14 on 2026-05-11 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0026_alter_appuser_options_alter_appuser_driver_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanicAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitud al activar la alerta')),
                ('longitude', models.FloatField(help_text='Longitud al activar la alerta')),
                ('address', models.CharField(blank=True, help_text='Dirección aproximada (geocodificación inversa)', max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('attended', 'Atendida'), ('resolved', 'Resuelta'), ('false_alarm', 'Falsa Alarma')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas del operador sobre la alerta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attended_by', models.ForeignKey(blank=True, help_text='Admin que atendió la alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_panic_alerts', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(help_text='Conductor que activó la alerta', limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='panic_alerts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Cooperativa del conductor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panic_alerts', to='taxis.organization')),
                ('ride', models.ForeignKey(blank=True, help_text='Carrera activa al momento de la alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panic_alerts', to='taxis.ride')),
            ],
            options={
                'verbose_name': 'Alerta de Pánico',
                'verbose_name_plural': 'Alertas de Pánico',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideTrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token único para acceder al link (ej: a7h2k9l1)', max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si el link está activo (se desactiva al completar la carrera)')),
                ('views_count', models.IntegerField(default=0, help_text='Número de veces que se ha abierto el link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del link', null=True)),
                ('ride', models.ForeignKey(help_text='Carrera que se está rastreando', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='taxis.ride')),
            ],
            options={
                'verbose_name': 'Link de Seguimiento',
                'verbose_name_plural': 'Links de Seguimiento',
                'ordering': ['-created_at'],
            },
        ),
    ]
