"""Ejemplo de migración para agregar campos de media al modelo ChatMessage
Ejecutar: python manage.py makemigrations
Luego: python manage.py migrate"""

# Generated by Django X.X.X on YYYY-MM-DD HH:MM

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0017_chatmessage'),  # Ajusta según tu última migración
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(
                choices=[
                    ('text', 'Texto'),
                    ('image', 'Imagen'),
                    ('video', 'Video'),
                    ('audio', 'Audio'),
                    ('file', 'Archivo'),
                ],
                default='text',
                help_text='Tipo de mensaje: texto, imagen, video, etc.',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='media_url',
            field=models.URLField(
                blank=True,
                help_text='URL del archivo multimedia (imagen, video, etc.)',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thumbnail_url',
            field=models.URLField(
                blank=True,
                help_text='URL del thumbnail (para videos o imágenes grandes)',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Metadatos adicionales: {width, height, size, duration, format, etc.}',
                null=True
            ),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(
                fields=['message_type'],
                name='taxis_chatm_message_idx'
            ),
        ),
    ]

